#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(SKILL_SWAP) \
    F(SNATCH) \
    F(OVERHEAT) \
	F(ACROBATICS) \
	F(FLAME_CHARGE) \
	F(INCINERATE) \
	F(SLUDGE_WAVE) \
	F(DARK_PULSE) \
	F(FROST_BREATH) \
	F(X_SCISSOR) \
	F(CHARGE_BEAM) \
	F(VENOSHOCK) \
	F(CRUNCH) \
	F(DRAGON_PULSE) \
	F(EARTH_POWER) \
	F(ENERGY_BALL) \
	F(DAZZLING_GLEAM) \
	F(POWER_UP_PUNCH) \
	F(SCALD) \
	F(NASTY_PLOT) \
	F(WILD_CHARGE) \
	F(DREAM_EATER) \
	F(FLASH_CANNON) \
	F(U_TURN) \
	F(POISON_JAB) \
	F(DRAGON_TAIL) \
	F(ECHOED_VOICE) \
	F(SWORDS_DANCE) \
	F(STRUGGLE_BUG) \
	F(HONE_CLAWS) \
	F(STONE_EDGE) \
	F(SHADOW_CLAW) \
	F(LOW_SWEEP) \
	F(GIGA_IMPACT) \
	F(FOCUS_BLAST) \
	F(CROSS_POISON) \
	F(DUAL_WINGBEAT) \

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
